.de EX
.ne 5
.if n .sp 1
.if t .sp .5
.nf
.in +.5i
..
.de EE
.fi
.in -.5i
.if n .sp 1
.if t .sp .5
..
.TH MAURICIO-WALL 1 "May 14, 2016"
.SH NAME
gwallpaper \- Wallpaper selector.
.SH SYNOPSIS
.B gwallpaper
.RI EXPRESSION|COMMAND
.RI [OPTIONS]
.SH DESCRIPTION
gwallpaper is a part of mauricio-wall API which allows you to setup gnome wallpaper
libraries by either function name, or by approximate type signature.
.EE
Example searches with EXPRESSION:
.EX

    gwallpaper
    (a -> b) -> [a] -> [b]
    Ord a => [a] -> [a]
    Data.Map.insert

.EE
The gwallpaper manual (http://www.google.co.uk/search?q=mauricio-wall) contains more
details, including further details on search queries, how to install gwallpaper as
a command line application and how to integrate gwallpaper with Firefox/Emacs/Vim
etc.
.PP
This program also does not have any command for special usage, these is just dummy manpage.
.SS "Command reference:"
.TP
\fBdata\fR
Generate Hoogle databases
.TP
\fBserver\fR
Start a Hoogle server
.TP
\fBcombine\fR
Combine multiple databases into one
.TP
\fBconvert\fR
Convert an input file to a database
.TP
\fBtest\fR
Run tests
.TP
\fBdump\fR
Dump sections of a database to stdout
.TP
\fBrank\fR
Generate ranking information
.TP
\fBlog\fR
Analyse log files
.SS "Option reference:"
.TP
\fB\-\fR?, \fB\-\-help\fR
Show help message
.TP
\fB\-V,\-\-version\fR
Print out version information
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Display verbose information
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Quiet verbosity
.SH AUTHOR
The text for this page was constructed from the Hoogle search engine's web page
and written by Erik de Castro Lopo <erikd@mega-nerd.com> and Kiwamu Okabe
<kiwamu@debian.or.jp>, for the Debian GNU/Linux system (but may be used by
others).
.SH "SEE ALSO"
.LP
haddock(1), update-hoogle(8)
